ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-{{ env }}.daws88c.online
CATALOGUE_HOST: catalogue-{{ env }}.daws88c.online
REDIS_HOST: redis-{{ env }}.daws88c.online
USER_HOST: user-{{ env }}.daws88c.online
CART_HOST: cart-{{ env }}.daws88c.online
MYSQL_HOST: mysql-{{ env }}.daws88c.online
SHIPPING_HOST: shipping-{{ env }}.daws88c.online
RABBITMQ_HOST: rabbitmq-{{ env }}.daws88c.online
PAYMENT_HOST: payment-{{ env }}.daws88c.online
app_version: v3