[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.daws88c.online

[redis]
local

[cart]
cart-dev.daws88c.online

[user]
user-dev.daws88c.online

[mysql]
mysql-dev.daws88c.online

[shipping]
shipping-dev.daws88c.online

[rabbitmq]
rabbitmq-dev.daws88c.online

[payment]
payment-dev.daws88c.online

[frontend]
frontend-dev.daws88c.online

[all:vars]
REDIS_HOST=redis-dev.daws88c.online
USER_HOST=user-dev.daws88c.online
CART_HOST=cart-dev.daws88c.online
MYSQL_HOST=mysql-dev.daws88c.online
SHIPPING_HOST=shipping-dev.daws88c.online
RABBITMQ_HOST=rabbitmq-dev.daws88c.online
PAYMENT_HOST=payment-dev.daws88c.online